services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - HUGGING_FACE_API_KEY=${HUGGING_FACE_API_KEY}
      - APP_KEY=${APP_KEY:-}
    networks:
      - laravel_net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d laravel"]
      interval: 5s
      timeout: 5s
      retries: 20

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public:ro
    ports:
      - "8080:80"
    networks:
      - laravel_net
    depends_on:
      - app

networks:
  laravel_net:

volumes:
  pgdata: